dev:
  name: news_aggregator_dev
  user: news_admin_dev
  password: fasldkflk423mkj4k24jk242
  host: localhost
  port: 5432
  pool:
    min_connections: 1
    max_connections: 10
    idle_timeout: 300

production:
  name: news_aggregator_prod
  user: news_admin_prod  
  password: fasldkflk423mkj4k24jk242
  host: localhost
  port: 5432
  pool:
    min_connections: 5
    max_connections: 50
    idle_timeout: 300

shared:
  application_name: news_aggregator
  connect_timeout: 10
  statement_timeout: 30000
  idle_in_transaction_session_timeout: 60000
  ssl_mode: disable
