development:
  root:
    level: DEBUG
    handlers: [console, file]
  
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/news_aggregator_dev.log
      maxBytes: 10485760  # 10MB
      backupCount: 5

  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

production:
  root:
    level: INFO
    handlers: [console, file]
  
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: detailed
      filename: logs/news_aggregator_prod.log
      maxBytes: 52428800  # 50MB
      backupCount: 10

  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
