nyt:
  base_url: https://www.nytimes.com
  rss_url: https://rss.nytimes.com/services/xml/rss/nyt
  rate_limit:
    requests_per_day: 4000
    requests_per_minute: 60

bbc:
  base_url: https://www.bbc.com
  rss_base_url: https://feeds.bbci.co.uk
  rate_limit:
    requests_per_minute: 30

cnn:
  base_url: https://edition.cnn.com
  html_selectors:
    nav: nav.subnav
    section: li.subnav__section
    subsection: li.subnav__subsection
  rate_limit:
    requests_per_minute: 100

guardian:
  base_url: https://www.theguardian.com
  rss_base_url: https://www.theguardian.com/rss
  rate_limit:
    requests_per_minute: 500

reuters:
  base_url: https://www.reuters.com
  api_base_url: https://api.reuters.com/v2
  rate_limit:
    requests_per_minute: 60

defaults:
  timeout: 30
  retries: 3
  backoff_factor: 2
  user_agents:
    - 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    - 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    - 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0'
