# summarizer_prompt.py

def create_prompt(content, article_length):
    """
    Create a detailed prompt for summarizing article content with strict HTML formatting requirements.
    
    Parameters:
    - content (str): The article content to be summarized.
    - article_length (int): The length of the article, which may trigger additional formatting restrictions if > 5000.
    
    Returns:
    - str: A prompt that instructs on generating an HTML formatted summary.
    """
    prompt = (
        "Create a focused, visually enhanced summary of the main topic from the following text using these guidelines:\n\n"
        
        "MAIN TOPIC IDENTIFICATION:\n"
        "1. Determine the central topic by analyzing the article title, introductory paragraphs, and recurring themes or keywords.\n"
        "2. Focus exclusively on the main narrative thread of the article, ignoring unrelated content that appears later.\n"
        "3. Pay attention to structural indicators that signal the end of the main article content.\n"
        "4. IMPORTANT: Only extract and include entities that are directly relevant to the core topic. DO NOT include entities that are merely mentioned in passing, appear in sidebar content, or are irrelevant to the main narrative.\n"
        "Example: If the article discusses a company's financial turnaround, identify 'financial turnaround' as the central topic.\n\n"
    )
    if article_length > 5000:
        prompt += (
            "CRITICAL FOR LONGER ARTICLES - FORMAT RESTRICTIONS:\n"
            "1. Return ONLY valid, complete HTML content with no markdown formatting whatsoever.\n"
            "2. DO NOT start your response with titles or headings outside of HTML tags.\n"
            "3. Ensure ALL formatting is done using HTML elements only.\n"
            "4. Wrap your entire response in a single <div> element.\n"
            "5. Do not include ```html code blocks or any markdown syntax.\n"
            "6. Never use 'The article discusses the' or simillar phrases to start your response. Just give summary without relating to source. \n"
            "Example: <div><h1>Example Title</h1><p>Content here...</p></div>\n\n"
        )
    prompt += (
        "ENGAGING TITLE:\n"
        "1. Create an intriguing title as an H1 HTML element.\n"
        "2. The title should directly relate to the central issue or conflict in the article.\n"
        "3. Make it compelling and descriptive; it can be longer if needed and does not have to be in question format.\n"
        "Example: <h1>The Rise and Fall of a Tech Giant: A Story of Innovation and Intrigue</h1>\n\n"
        
        "SOURCE ATTRIBUTION SECTION:\n"
        "1. Immediately after the title, create a section for source attribution.\n"
        "2. Use the format: '<p style=\"color:#555555; font-style:italic; font-size:0.9em;\">Source: [ORIGINAL SOURCE] | Published: [DATE]</p>'\n"
        "3. For the original source, apply these STRICT guidelines:\n"
        "   - NEVER attribute to any news portals, websites, news organizations, or media outlets (such as The New York Times, BBC, PBS, etc.)\n"
        "   - NEVER attribute to photography sources, photographers, or image credits\n"
        "   - DO attribute to the most prominent organization mentioned in the title or first paragraph\n"
        "   - If no organization is in the title, use the most relevant organization from the article content\n"
        "   - For government sources, ALWAYS specify which government (e.g., 'U.S. Department of Treasury' not just 'Government')\n"
        "   - Valid sources include: specific companies, named government agencies, industry associations, research institutions, regulatory bodies\n"
        "4. For the date:\n"
        "   - Use the format 'Month DD, YYYY' if the exact date is available\n"
        "   - If only the month and year are known, use 'Month YYYY'\n"
        "   - If date is completely unknown, use the current month and year (e.g., 'March 2025')\n"
        "5. Examples of CORRECT attribution:\n"
        "   - <p style=\"color:#555555; font-style:italic; font-size:0.9em;\">Source: Tesla, Inc. | Published: January 15, 2023</p>\n"
        "   - <p style=\"color:#555555; font-style:italic; font-size:0.9em;\">Source: U.S. Department of Defense | Published: March 2025</p>\n"
        "   - <p style=\"color:#555555; font-style:italic; font-size:0.9em;\">Source: World Health Organization | Published: February 2025</p>\n"
        "6. Examples of INCORRECT attribution (NEVER use these formats):\n"
        "   - Source: The New York Times | Published: April 26, 2024 (✗ - news portal)\n"
        "   - Source: Government Review | Published: February 28, 2024 (✗ - non-specific government)\n"
        "   - Source: James Lester Photography | Published: 2024 (✗ - photography source)\n\n"
        
        "KEYWORDS SECTION:\n"
        "1. After the source attribution, create a section with the heading '<strong>Keywords:</strong>' (the word 'Keywords:' must be bold).\n"
        "2. List the 5-10 most frequently appearing significant words or phrases from the article that are DIRECTLY RELATED to the main topic.\n"
        "3. Present these as a comma-separated inline list in default (black) text, without using bullet points or numbering.\n"
        "4. End this section with a horizontal line (<hr>).\n"
        "Example: <p><strong>Keywords:</strong> innovation, turnaround, profit, market, growth</p><hr>\n\n"
        
        "ENTITY OVERVIEW SECTION:\n"
        "0. Identify and classify all key entities from the text into these categories, STRICTLY focusing on entities relevant to the CORE topic:\n"
        "   - NAMED INDIVIDUALS: Specific people mentioned by name who are central to the main story.\n"
        "   - ROLES & CATEGORIES: Occupations, types of people, or classifications that play a significant role in the core narrative.\n"
        "   - ORGANIZATIONS & PRODUCTS: Companies, brands, product types, and services that are directly involved in the main topic.\n"
        "   - LOCATIONS: Countries, cities, regions, or specific geographical places where key events in the main story occur.\n"
        "   - TIME PERIODS & EVENTS: Specific dates, time periods, seasons, or notable events that frame the central narrative.\n"
        "   - ARTISTIC CONCEPTS & DESIGN ELEMENTS: Aesthetic principles, design philosophies, or artistic movements central to the main topic.\n"
        "   - INDUSTRY TERMINOLOGY: Specialized terms and jargon specific to the industry being discussed that are essential to understanding the core topic.\n"
        "   - FINANCIAL & BUSINESS TERMS: Important business metrics, financial concepts, or market terminology directly relevant to the main narrative.\n"
        "   - KEY ACTIONS & RELATIONSHIPS: Verbs that show important actions or relationships between key entities in the core story.\n"
        "1. CRITICAL: Only include entities that are genuinely relevant to the core topic. Exclude entities that appear in tangential discussions, background information, or unrelated sections.\n"
        "2. Track the frequency and prominence of each entity throughout the text.\n"
        "3. Rank entities within each category based on importance (using factors such as frequency, prominence in headlines, or early mentions).\n"
        "Examples:\n"
        "   - For NAMED INDIVIDUALS, list: <strong style=\"color:#D55E00\"><u>John Doe</u></strong>, <strong style=\"color:#D55E00\"><u>Jane Smith</u></strong>.\n"
        "   - For ROLES & CATEGORIES, list: <strong style=\"color:#0072B2\">Founder</strong>, <strong style=\"color:#0072B2\">Accountant</strong>.\n"
        "   - For ORGANIZATIONS & PRODUCTS, list: <strong style=\"color:#009E73\">TechCorp</strong>, <strong style=\"color:#009E73\">GadgetPro</strong>.\n"
        "   - For LOCATIONS, list: <strong style=\"color:#56B4E9\">New York</strong>, <strong style=\"color:#56B4E9\">Tokyo</strong>.\n"
        "   - For TIME PERIODS & EVENTS, list: <strong style=\"color:#E69F00\">2023</strong>, <strong style=\"color:#E69F00\">Fashion Week</strong>.\n"
        "   - For ARTISTIC CONCEPTS & DESIGN ELEMENTS, list: <strong style=\"color:#F0E442\">minimalism</strong>, <strong style=\"color:#F0E442\">avant-garde</strong>.\n"
        "   - For INDUSTRY TERMINOLOGY, list: <strong style=\"color:#8AE68A\">haute couture</strong>, <strong style=\"color:#8AE68A\">ready-to-wear</strong>.\n"
        "   - For FINANCIAL & BUSINESS TERMS, list: <strong style=\"color:#666666\">acquisition</strong>, <strong style=\"color:#666666\">market share</strong>.\n"
        "   - For KEY ACTIONS & RELATIONSHIPS, list: <strong style=\"color:#CC79A7\">acquired</strong>, <strong style=\"color:#CC79A7\">merged</strong>.\n\n"
    
        "1. Create a section with the heading '<strong>Entity Overview:</strong>' (the heading must be bold).\n"
        "2. List all identified entities, organized by the nine categories. Each category must be presented on its own line.\n"
        "   - The category name must be bolded and displayed in its designated color, followed by a colon and a comma-separated list of entities.\n"
        "   - DO NOT use bullet points or numbering in this section.\n"
        "   - If a particular category has no relevant entities for the core topic, indicate this with 'None identified' after the colon.\n"
        "3. Use the same color coding for each category as specified in the Legend section.\n"
        "4. Provide full examples for every category as follows:\n"
        "   - NAMED INDIVIDUALS Example: \n"
        "     <p><strong style=\"color:#D55E00\">Named Individuals:</strong> "
        "<strong style=\"color:#D55E00\"><u>John Doe</u></strong>, "
        "<strong style=\"color:#D55E00\"><u>Jane Smith</u></strong></p>\n"
        "   - ROLES & CATEGORIES Example: \n"
        "     <p><strong style=\"color:#0072B2\">Roles & Categories:</strong> "
        "<strong style=\"color:#0072B2\">Founder</strong>, "
        "<strong style=\"color:#0072B2\">Accountant</strong></p>\n"
        "   - ORGANIZATIONS & PRODUCTS Example: \n"
        "     <p><strong style=\"color:#009E73\">Organizations & Products:</strong> "
        "<strong style=\"color:#009E73\">TechCorp</strong>, "
        "<strong style=\"color:#009E73\">GadgetPro</strong></p>\n"
        "   - LOCATIONS Example: \n"
        "     <p><strong style=\"color:#56B4E9\">Locations:</strong> "
        "<strong style=\"color:#56B4E9\">New York</strong>, "
        "<strong style=\"color:#56B4E9\">Tokyo</strong></p>\n"
        "   - TIME PERIODS & EVENTS Example: \n"
        "     <p><strong style=\"color:#E69F00\">Time Periods & Events:</strong> "
        "<strong style=\"color:#E69F00\">2023</strong>, "
        "<strong style=\"color:#E69F00\">Fashion Week</strong></p>\n"
        "   - ARTISTIC CONCEPTS & DESIGN ELEMENTS Example: \n"
        "     <p><strong style=\"color:#F0E442\">Artistic Concepts & Design Elements:</strong> "
        "<strong style=\"color:#F0E442\">minimalism</strong>, "
        "<strong style=\"color:#F0E442\">avant-garde</strong></p>\n"
        "   - INDUSTRY TERMINOLOGY Example: \n"
        "     <p><strong style=\"color:#8AE68A\">Industry Terminology:</strong> "
        "<strong style=\"color:#8AE68A\">haute couture</strong>, "
        "<strong style=\"color:#8AE68A\">ready-to-wear</strong></p>\n"
        "   - FINANCIAL & BUSINESS TERMS Example: \n"
        "     <p><strong style=\"color:#666666\">Financial & Business Terms:</strong> "
        "<strong style=\"color:#666666\">acquisition</strong>, "
        "<strong style=\"color:#666666\">market share</strong></p>\n"
        "   - KEY ACTIONS & RELATIONSHIPS Example: \n"
        "     <p><strong style=\"color:#CC79A7\">Key Actions & Relationships:</strong> "
        "<strong style=\"color:#CC79A7\">acquired</strong>, "
        "<strong style=\"color:#CC79A7\">merged</strong></p>\n"
        "5. End this section with a horizontal line (<hr>).\n\n"
        
        "SUMMARY CREATION:\n"
        "1. Create a section with the heading '<strong>Summary:</strong>' (the heading must be bold).\n"
        "2. Write a focused, engaging summary that addresses ONLY the central topic identified earlier.\n"
        "3. Structure your summary with a specific format:\n"
        "   - FIRST PARAGRAPH: Present the core meaning or main point of the article concisely. This should capture the essential message or conclusion that readers should take away.\n"
        "   - SUBSEQUENT PARAGRAPHS: Elaborate on what happened, providing supporting details, context, and development of the main point.\n"
        "4. Include important details such as names, numbers, dates, organizations, and relationships related to the main topic.\n"
        "5. Format all named individuals as bold AND underlined in their designated color (#D55E00) using EXACTLY this format: '<strong style=\"color:#D55E00\"><u>Name</u></strong>'.\n"
        "6. Format all other entities according to their respective categories with appropriate colors as defined in the Entity Overview section.\n"
        "7. Use simple language and avoid overly complex or long sentences.\n"
        "8. IMPORTANT: Only reference entities that are directly relevant to the core topic. Do not mention entities that appeared in passing or in tangential discussions.\n"
        "9. End this section with a horizontal line (<hr>).\n"
        "10. You  must use smaller paragraphs even with shorter summaries. \n"
        "11. If possible provide context for the entities mentioned in the summary. \n"
        "12. Make larger summary if the article is longer - it's more important not to miss and relvant information. \n"
        "Every entity mentioned in 'ENTITY OVERVIEW SECTION' should also be present and properly formatted in the summary. \n"
        "Example: <p>The article explores the dramatic financial turnaround of a major corporation. It highlights how <strong style=\"color:#D55E00\"><u>John Doe</u></strong>, a visionary <strong style=\"color:#0072B2\">leader</strong>, spearheaded changes in <strong style=\"color:#56B4E9\">New York</strong> during <strong style=\"color:#E69F00\">2023</strong>, embracing <strong style=\"color:#F0E442\">minimalism</strong> in their approach to <strong style=\"color:#8AE68A\">product development</strong>, which led to a successful <strong style=\"color:#666666\">market expansion</strong> when they <strong style=\"color:#CC79A7\">acquired</strong> smaller competitors.</p><hr>\n\n"
        
        "INTERESTING FACTS SECTION:\n"
        "1. Create a section with the heading '<strong>Interesting Facts:</strong>' (the heading must be bold).\n"
        "2. List 5-10 additional interesting facts in bullet form that are related to the core story but not covered in the summary.\n"
        "3. Present each fact as a concise, simple statement on its own line within bullet points (<li> elements inside a <ul> container).\n"
        "4. Apply the same entity formatting as in the summary section for any entities mentioned in the facts.\n"
        "5. IMPORTANT: Only include facts that are directly relevant to the core topic. Exclude tangential or passing mentions.\n"
        "6. End this section with a horizontal line (<hr>).\n"
        "Example:\n"
        "   <ul>\n"
        "       <li><strong style=\"color:#D55E00\"><u>John Doe</u></strong> was the youngest <strong style=\"color:#0072B2\">CEO</strong> in his industry in <strong style=\"color:#E69F00\">2018</strong>.</li>\n"
        "       <li><strong style=\"color:#009E73\">Company XYZ</strong> set a record for quarterly <strong style=\"color:#666666\">profits</strong> in <strong style=\"color:#56B4E9\">Silicon Valley</strong>.</li>\n"
        "   </ul><hr>\n\n"
        
        "LEGEND SECTION:\n"
        "1. Create a section with the heading '<strong>Legend:</strong>' (the heading must be bold).\n"
        "2. List the nine entity types in a comma-separated inline list, each styled in its designated color without any additional explanations:\n"
        "   - '<strong style=\"color:#D55E00\">Named Individuals</strong>'\n"
        "   - '<strong style=\"color:#0072B2\">Roles & Categories</strong>'\n"
        "   - '<strong style=\"color:#009E73\">Organizations & Products</strong>'\n"
        "   - '<strong style=\"color:#56B4E9\">Locations</strong>'\n"
        "   - '<strong style=\"color:#E69F00\">Time Periods & Events</strong>'\n"
        "   - '<strong style=\"color:#F0E442\">Artistic Concepts & Design Elements</strong>'\n"
        "   - '<strong style=\"color:#8AE68A\">Industry Terminology</strong>'\n"
        "   - '<strong style=\"color:#666666\">Financial & Business Terms</strong>'\n"
        "   - '<strong style=\"color:#CC79A7\">Key Actions & Relationships</strong>'\n"
        "Example: <p><strong style=\"color:#D55E00\">Named Individuals</strong>, <strong style=\"color:#0072B2\">Roles & Categories</strong>, <strong style=\"color:#009E73\">Organizations & Products</strong>, <strong style=\"color:#56B4E9\">Locations</strong>, <strong style=\"color:#E69F00\">Time Periods & Events</strong>, <strong style=\"color:#F0E442\">Artistic Concepts & Design Elements</strong>, <strong style=\"color:#8AE68A\">Industry Terminology</strong>, <strong style=\"color:#666666\">Financial & Business Terms</strong>, <strong style=\"color:#CC79A7\">Key Actions & Relationships</strong></p>\n\n"
        
        "FORMATTING ENFORCEMENT - CRITICAL:\n"
        "1. The formatting requirements specified above MUST be followed exactly with no exceptions.\n"
        "2. All section headings MUST be bold and exactly as specified.\n"
        "3. Entity lists MUST be comma-separated without bullet points or numbering.\n"
        "4. Named individuals MUST be formatted as both bold and underlined in their color (#D55E00) using EXACTLY this format: '<strong style=\"color:#D55E00\"><u>Name</u></strong>'.\n"
        "5. All other entities MUST be formatted as bold only in their designated colors using the exact formats provided.\n"
        "6. The summary MUST be composed of proper paragraphs.\n"
        "7. Horizontal lines (<hr>) MUST be placed between sections exactly as specified.\n"
        "8. There MUST NOT be any nested or duplicate HTML tags.\n"
        "9. Any deviation from these formatting requirements is unacceptable.\n"
        "Strictly use HTML for all formatting; do not use markdown or any other formatting method.\n"
        "Ensure the final output is a valid HTML document that is visually appealing and well-structured.\n"
        "Focus on creating an engaging and informative summary that clearly highlights the main topic.\n\n"
        
        "ARTICLE CONTENT:\n" + content
    )
    return prompt